# Generated by Django 5.0.4 on 2024-04-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('occur_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('p_type', models.IntegerField()),
                ('start_date', models.DateField()),
                ('term_month', models.IntegerField()),
                ('rate', models.IntegerField(default=0)),
                ('currency', models.IntegerField(default=0, null=True)),
                ('ctype', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
