# Generated by Django 5.0.4 on 2024-05-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='occur_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prop',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
