# Generated by Django 5.0.4 on 2024-05-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_detail_occur_date_alter_prop_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='occur_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prop',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
