# Generated by Django 5.0.4 on 2024-05-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_detail_occur_date_alter_prop_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prop'),
        ),
    ]
