# Generated by Django 5.0.4 on 2024-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_detail_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
