# Generated by Django 5.1 on 2025-08-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_prop_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
